### ISSUE TITLE
help does not work

### ISSUE THREAD

**Issue by popopopotuf** [sysplu/Nullify#108]

**Comment by baldwinT12** [comment]
mine 2 . But sometimes is work but I get this message     "  SecurityError: Blocked a frame with origin "https://login.i-ready.com" from accessing a cross-origin frame.  "

**Comment by binary-pumpkin** [comment]
same here

**Comment by baldwinT12** [comment]
" fr ".  Please @sysplu help us out, please



thx!!!!!!!!!!
