### ISSUE TITLE
Minute farmer is broken [BUG]

### ISSUE THREAD

**Issue by M4rrHax** [sysplu/Nullify#116]
The minute farmer hack does not work as the lesson goes to the "are you still there?" screen please fix this

**Comment by uwugirl2020** [comment]
the skip the lesson dont work either

**Comment by M4rrHax** [comment]
> the skip the lesson dont work either

it works well for me delete the bookmarklet and add it back or refresh your page and try again

**Comment by uwugirl2020** [comment]
done let me try

**Comment by uwugirl2020** [comment]
nope dont work

**Comment by cupiditys** [comment]
updated
