### ISSUE TITLE
[BUG] Error Message: Something’s wrong. Tap the green arrow button or ask your teacher for help.

### ISSUE THREAD

**Issue by dannnieleelle** [sysplu/Nullify#117]
When pressing skip lesson and typing in my score, it prompts me to this error message. I’m using the code bookmarklet on the front page and it opens completely fine. But the ‘Skip Lesson’ feature unfortunately doesn’t work for me for some reason. I tried refreshing multiple times, close all my windows/tabs and trying again. I’m using my school’s computer which is a Dell laptop. And I’m using version 3.2b of Nullify. Any ideas on fixes?? 
![image](https://user-images.githubusercontent.com/129145592/228138324-e41cdb0c-999b-44e5-865d-ae92a883e12e.jpg)

**Comment by uwugirl2020** [comment]
same here

**Comment by uwugirl2020** [comment]
the minute farmer works but skip lesson dosent

**Comment by cupiditys** [comment]
farm
