### ISSUE TITLE
ned help and skip lesson aint working math or radig after i rest and took out of the bookmark i need to know the working link pls[BUG]

### ISSUE THREAD

**Issue by uwugirl2020** [sysplu/Nullify#121]
**Describe the bug**
What went wrong?

**To Reproduce**
Steps to reproduce the bug:

**Expected behavior**
What did you expect to happen?

**Screenshots/video**
If applicable, add screenshots or a video to help explain your problem.

**Info**
Which version of nullify are you using?
are you using a personal computer or a school computer?

**Comment by cupiditys** [comment]
updated
