### ISSUE TITLE
[BUG] Hackers are outmatched 

### ISSUE THREAD

**Issue by CupditysDaysNumbered** [sysplu/Nullify#123]
**Describe the bug**
What went wrong

daily fixes needed because they are fumbling in the dark

**To Reproduce**
Steps to reproduce the bug:

Have a middle school education and go up against a large US company 

**Expected behavior*

run

What did you expect to happen?

more failure by cupidity, a lack of a social life or meaningful value to society outside this sad project 

**Screenshots/video**
If applicable, add screenshots or a video to help explain your

**Info**
Which version of nullify are you using?
are you using a personal computer or a school computer?

**Comment by sheepsushis** [comment]
op has a point
