### ISSUE TITLE
[BUG] BWHAHAHA

### ISSUE THREAD

**Issue by CupditysDaysNumbered** [sysplu/Nullify#128]
**Describe the bug**
What went wrong?

**To Reproduce**
Steps to reproduce the bug:

**Expected behavior**
What did you expect to happen?

**Screenshots/video**
If applicable, add screenshots or a video to help explain your problem.

**Info**
Which version of nullify are you using?
are you using a personal computer or a school computer?

**Comment by cupiditys** [comment]
when bro realizes 90% of people who do iready live on the east coast
