### ISSUE TITLE
bhwahahahha

### ISSUE THREAD

**Issue by CupditysDaysNumbered** [sysplu/Nullify#130]
**Describe the bug**
What went wrong?

**To Reproduce**
Steps to reproduce the bug:

**Expected behavior**
What did you expect to happen?

**Screenshots/video**
If applicable, add screenshots or a video to help explain your problem.

**Info**
Which version of nullify are you using?
are you using a personal computer or a school computer?

**Comment by cupiditys** [comment]
Can you give me my location please i forgot

**Comment by CupditysDaysNumbered** [comment]
you'll find out soon enough bruh

**Comment by cupiditys** [comment]
stop opening issues or ur gonna get blocked just reply here when ur giving my "location"
