### ISSUE TITLE
I feel retarded, but where is the bookmarklet script for nullify?

### ISSUE THREAD

**Issue by XeonIsYummy** [sysplu/Nullify#131]
**Describe the bug**
I was born
**To Reproduce**
Steps to reproduce the bug:
Become retarded 

**Expected behavior**
To be infront of it
**Screenshots/video**
Nope
**Info**
Which version of nullify are you using?
School pc

**Comment by miconguyen** [comment]
where is the bookmarklet code

**Comment by cupiditys** [comment]
there is no more bookmarklet
