### ISSUE TITLE
windows antivirus

### ISSUE THREAD

**Issue by erectyle** [sysplu/Nullify#134]
It wont download because it detected a virus and i dont feel like downloading cause it feels sketchy  asf

**Comment by XeonIsYummy** [comment]
Start the revolt, Add back the bookmarklet

**Comment by Dizzyiou** [comment]
discord.gg/nullify

**Comment by cupiditys** [comment]
microsoft says theyve removed the false detection
https://cdn.discordapp.com/attachments/1088838359528525824/1090839104608030780/image.png
