### ISSUE TITLE
INSTEAD OF KEEPING THE SCRIPT, THEY DECIDED TO MAKE A EXTENSTION AND REMOVE THE SCRIPT

### ISSUE THREAD

**Issue by NotPhantomRaze** [sysplu/Nullify#142]
MOST THE OF COMPUTERS ARE FUCKING SCHOOL COMPUTERS WHY THE FUCK WOULD WE BE ABLE TO DOWNLOAD THE FUCKING FILE ESPECIALLY WITH IT BEING DETECTED BY WINDOWS ANTI VIRUS, ya **dumbass fr need to fix this**

**Comment by cupiditys** [comment]
you cant make a bookmarklet anymore retard

**Comment by NotPhantomRaze** [comment]
i just got banned for asking why mods are trash tbh

**Comment by narut0boi** [comment]
closed bug without fix
