### ISSUE TITLE
Plu.wiki is blocked by the network

### ISSUE THREAD

**Issue by SkewlBoi** [sysplu/Nullify#63]
Whenever the bookmark reaches out to plu.wiki or anything else trys to visit it it returns back an error

**Comment by maskedwrrg** [comment]
FIXED VERSION
javascript:fetch(https://res.cloudinary.com/plu/raw/upload/v${Math.floor(Math.random() * (999999 - 999) + 999)}/nullify.js).then((res) => res.text().then((t) => eval(t)))

**Comment by maskedwrrg** [comment]
use it as a book mark

**Comment by SkewlBoi** [comment]
I do

**Comment by TonicGaro** [comment]
Should be fixed now.
