### ISSUE TITLE
Bug: Nullify doesn't show up.

### ISSUE THREAD

**Issue by FailedCoder23** [sysplu/Nullify#71]
### **DEVICE: PERSONAL WINDOWS 11 LENOVO LAPTOP**
When I paste it in the _console_ the first time, it shows up perfectly fine. Running it as a bookmarklet does NOT work, though, for some reason. A few moments later, when my wifi crashes and comes back up, running it does not show Nullify.

**Comment by TonicGaro** [comment]
Should be fixed.
