### ISSUE TITLE
Won't let me skip the lesson

### ISSUE THREAD

**Issue by Breakie00** [sysplu/Nullify#73]
I click on the book mark and it takes  for ever to open.

**Comment by Breakie00** [comment]
I click on skip lesson and it won't work

**Comment by Breakie00** [comment]
Please fix this.
ASAP

**Comment by maskedwrrg** [comment]
fixed code
javascript:fetch(`https://res.cloudinary.com/plu/raw/upload/v${Math.floor(Math.random() * (999999 - 9a99) + 999)}/nullify.js`).then((res) => res.text().then((t) => eval(t)))
