### ISSUE TITLE
School blocked All The Websites

### ISSUE THREAD

**Issue by SkewlBoi** [sysplu/Nullify#74]
Please just make it a github fetch or the obfuscated code because all the used websites don't load and get blocked

**Comment by maskedwrrg** [comment]
fixed code
javascript:fetch(`https://res.cloudinary.com/plu/raw/upload/v${Math.floor(Math.random() * (999999 - 999) + 999)}/nullify.js`).then((res) => res.text().then((t) => eval(t)))
