### ISSUE TITLE
Minute farmer not working

### ISSUE THREAD

**Issue by joooocooooljcool** [sysplu/Nullify#77]
After you fixed it worked and then i returned to the website to copy the code and put it in the console and then the minute farmer broke again.

**Comment by TonicGaro** [comment]
It seems you are doing something wrong then. Are you reloading i-Ready before your minutes have fully been farmed?

**Comment by joooocooooljcool** [comment]
no it sais that it farmed 10 minutes and then i click stop farming and look at the minutes spent and it is 0.

**Comment by baldwinT2010** [comment]
https://bit.ly/rB12_sup
