### ISSUE TITLE
It;s fixed but has a slight bug

### ISSUE THREAD

**Issue by SkewlBoi** [sysplu/Nullify#78]
The gui hide hotkey doesn't work. Nothing appears to happen but i don't know what is going on under the hood. Just a heads up

**Comment by TonicGaro** [comment]
It's cause the rest of the devs changed up some of the code and forgot to add the hide toggle back. Will be fixed soon.

**Comment by SkewlBoi** [comment]
Also teh skip lesson button doesn't skip the lesson it just gets highlighted and when you click it it doesn't do anything

**Comment by I-maker-o** [comment]
I want haaaaaaaaaaaaaaaaaaaaaacks!
