### ISSUE TITLE
the Java script doesn't do anything it dose not work

### ISSUE THREAD

**Issue by wackyomama** [sysplu/Nullify#82]

**Comment by ajhsduyiashx** [comment]
+same thing happened to me and my friends. the school might have blocked javascript  so anyway to bypass this?

**Comment by maskedwrrg** [comment]
maybe let me get back to you

**Comment by wackyomama** [comment]
but I can give you the unblocking cheat
1. [ ](chrome://settings/signOut)
2. [ ](chrome://restart)

**Comment by maskedwrrg** [comment]
wackyomama can you send me a video or something on how to use 
(chrome://settings/signOut)
(chrome://restart)

**Comment by wackyomama** [comment]
you have to make them a bookmarklet to separate bookmarklets you do the settings/sign out one first and the restart one second. and they can't block it or they will not have control of your Chromebooks well that's how it works at my school anyway, mite not for you idk.

**Comment by maskedwrrg** [comment]
oh so its for chromebooks\ we have macbookk air

**Comment by maskedwrrg** [comment]
so the code would be 
javascript:(chrome://settings/signOut)
javascript:(chrome://restart)

**Comment by wackyomama** [comment]
oh ok 
well anything on the IR hack
