### ISSUE TITLE
DOESN'T FREAKING WORK

### ISSUE THREAD

**Issue by OBAMA2200** [sysplu/Nullify#85]
THE HACKS WORK BUT DO NOT WORK AT ALL (IF THAT MAKES SENSE AT ALL).
BASICALLY IT ONLY SAYS FATAL ERROR

**Comment by OBAMA2200** [comment]
![Screenshot 2023-03-15 10 43 37 AM](https://user-images.githubusercontent.com/116755023/225363717-2b848860-119b-4283-80a5-0339b63bdee6.png)

**Comment by wackyomama** [comment]
mine doesn't even do that
