### ISSUE TITLE
I can't get it to work

### ISSUE THREAD

**Issue by parkermoodymtv** [sysplu/Nullify#97]
When I use the code on the main page it says "failed to fetch" and nothing happens, but when I use the code in `main.js` it still says "failed to fetch" but it loads the buttons (They don't work). 

Edit: I looked at the console errors, and it appears that my school has blocked https://raw.githubusercontent.com and that is why it breaks. Is there a way to fix this? Could I just paste the code inside of the string?

**Comment by cupiditys** [comment]
update
